# Generated by Django 4.1.4 on 2023-05-19 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('stream', models.CharField(max_length=1)),
                ('subject_1_name', models.CharField(max_length=50)),
                ('subject_1_marks', models.IntegerField()),
                ('subject_2_name', models.CharField(max_length=50)),
                ('subject_2_marks', models.IntegerField()),
                ('hollandCode1', models.CharField(max_length=20)),
                ('hollandCode2', models.CharField(max_length=20)),
                ('hollandCode3', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
